### ISSUE TITLE
Start button is not enabled when putting a key in

### ISSUE THREAD

**Issue by hbnordin2** [JinXJinX/BrainInVat#1] opened 2024-12-23 00:41 UTC
Reproduction steps:
- Download the plugin
- Put the api key in
- See that the start button stay grey and unclickable

**Comment by JinXJinX** [comment] 2024-12-30 19:19
Hi @hbnordin2 
Thank you for reporting the issue! The problem was caused by a change in the OpenAI API key format. I’ve updated the API key validator, and the fix is included in the latest version (v1.0.3). 

Let me know if you encounter any other issues. I really appreciate your feedback!

**Closed as completed by JinXJinX** 2024-12-30 19:19 UTC
